// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveSessionDates(arg1) {
  return window['go']['main']['App']['GetActiveSessionDates'](arg1);
}

export function GetActiveSessionHours(arg1, arg2) {
  return window['go']['main']['App']['GetActiveSessionHours'](arg1, arg2);
}

export function GetAdapterStatus() {
  return window['go']['main']['App']['GetAdapterStatus']();
}

export function GetAppDocumentStats(arg1, arg2) {
  return window['go']['main']['App']['GetAppDocumentStats'](arg1, arg2);
}

export function GetAppIcon(arg1) {
  return window['go']['main']['App']['GetAppIcon'](arg1);
}

export function GetAppSessionHistory(arg1, arg2) {
  return window['go']['main']['App']['GetAppSessionHistory'](arg1, arg2);
}

export function GetAppSessionsByTime(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAppSessionsByTime'](arg1, arg2, arg3);
}

export function GetAppUsageStats(arg1, arg2) {
  return window['go']['main']['App']['GetAppUsageStats'](arg1, arg2);
}

export function GetCategoryStats(arg1) {
  return window['go']['main']['App']['GetCategoryStats'](arg1);
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetRecentSessions(arg1) {
  return window['go']['main']['App']['GetRecentSessions'](arg1);
}

export function IsPaused() {
  return window['go']['main']['App']['IsPaused']();
}

export function ToggleTracking() {
  return window['go']['main']['App']['ToggleTracking']();
}
