// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAdapterStatus() {
  return window['go']['main']['App']['GetAdapterStatus']();
}

export function GetAppSessionHistory(arg1, arg2) {
  return window['go']['main']['App']['GetAppSessionHistory'](arg1, arg2);
}

export function GetAppUsageStats(arg1, arg2) {
  return window['go']['main']['App']['GetAppUsageStats'](arg1, arg2);
}

export function GetCategoryStats(arg1) {
  return window['go']['main']['App']['GetCategoryStats'](arg1);
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetRecentSessions(arg1) {
  return window['go']['main']['App']['GetRecentSessions'](arg1);
}

export function IsPaused() {
  return window['go']['main']['App']['IsPaused']();
}

export function ToggleTracking() {
  return window['go']['main']['App']['ToggleTracking']();
}
